### ISSUE TITLE
Mouse_event aimbot 

### ISSUE THREAD

**Issue by aguywith2tits** [dretax/GarHal_CSGO#112]
I believe it's super secure work with kernel + read only memory, so, I belive if you add the option, or just tell me how to add a mouse_event, or how to convert the view angles to mouse coordinates, it will very good, since writing to memory can be detected one day, like the bhop feature, and you can add the bhop feature again just sending a mouse scroll instead of forcing jump 😃

**Comment by dretax** [comment]
Write memory was never detected in VAC, and I'd legit say that kernel R/W directly would be insanly attrocious approach to even attempt to write "detections" for due to various logical reasons. I'd suggest understanding how the basic architecture works before suggesting such statements.

The way VAC detected W was that those flags shouldn't be true during a competitive match. The viewangles comparism, and legitimization would require atleast a server side check/implementation effort, the same way as EAC does in Rust.
I highly doubt you would even need to worry of such thing in VAC for the next millenia. Even if you would, you would humanize the aimbot by smoothing and calculating a set of view angles you write into the memory using bezier curve for example.
I have done the exact thing for Rust.

mouse_event is already being used for triggerbot, although I'm not quite sure if this would ever be the approach you should take.
