### ISSUE TITLE
About the GLOW and AIMBOT function, often undetectable behind the wall

### ISSUE THREAD

**Issue by 1145738769** [dretax/GarHal_CSGO#87]
I haven't play csgo for several but now I compile GARHAL csgo, GLOW and AIMBOT all frequent failure behind the wall, how can we repair

**Comment by dretax** [comment]
What the hell is this issue again. Are you serious?

**Comment by Life45** [comment]
> What the hell is this issue again. Are you serious?

why you no understand he say no work cheat it simple question u dumb

**Comment by dretax** [comment]
I think after reading this several times again he means:

1. GLOW doesn't work: This is due to csgo's isdormant function, if the server thinks you shouldn't see the player's position, you won't get an update on the character's current location.
2. Aimbot: It's due to the external check that it is now checking if you can see the player, or it is behind a wall. Do your research on how to disable this feature.

**Comment by Eurioin** [comment]
why not write in proper english? more understandable for everyone...
Is your probelm one of the following?

- [ ]  Does not work at all. 
- [ ]  Does work, but in a specified distance (e.g. on Dust2 from A site you can see players coming from long, but cant see players in B tunnel).
